name: Triage tasks

on: pull_request_target

concurrency:
  group: "triage-${{ github.event.number }}"
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  triage:
    environment: github_actions
    runs-on: ubuntu-slim
    steps:
      - name: Label pull request
        uses: Homebrew/actions/label-pull-requests@3cdb78d0f62ad29dd32de765782654f4eedea607 # 2026.08.31.1
        if: always()
        with:
          token: ${{ secrets.TOKEN }}
          def: |
            - label: ci-skip-install
              content: app_path

            - label: bump-cask-pr
              pr_body_content: Created with `brew bump-cask-pr`

            - label: missing description
              path: Casks/.+
              missing_content: \n  desc .+\n

            - label: missing zap
              path: Casks/.+
              missing_content: zap .+\n
